// ItemConstants.js

// Action types for item-related actions
const CREATE_ITEM_REQUEST = 'CREATE_ITEM_REQUEST';
const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';

const GET_ALL_ITEMS_REQUEST = 'GET_ALL_ITEMS_REQUEST';
const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
const GET_ALL_ITEMS_FAILURE = 'GET_ALL_ITEMS_FAILURE';

const GET_ITEM_BY_ID_REQUEST = 'GET_ITEM_BY_ID_REQUEST';
const GET_ITEM_BY_ID_SUCCESS = 'GET_ITEM_BY_ID_SUCCESS';
const GET_ITEM_BY_ID_FAILURE = 'GET_ITEM_BY_ID_FAILURE';

const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';

const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
const DELETE_ITEM_FAILURE = 'DELETE_ITEM_FAILURE';

module.exports = {
  CREATE_ITEM_REQUEST,
  CREATE_ITEM_SUCCESS,
  CREATE_ITEM_FAILURE,
  GET_ALL_ITEMS_REQUEST,
  GET_ALL_ITEMS_SUCCESS,
  GET_ALL_ITEMS_FAILURE,
  GET_ITEM_BY_ID_REQUEST,
  GET_ITEM_BY_ID_SUCCESS,
  GET_ITEM_BY_ID_FAILURE,
  UPDATE_ITEM_REQUEST,
  UPDATE_ITEM_SUCCESS,
  UPDATE_ITEM_FAILURE,
  DELETE_ITEM_REQUEST,
  DELETE_ITEM_SUCCESS,
  DELETE_ITEM_FAILURE,
};
