// OfferConstants.js

// Action types for offer-related actions
const CREATE_OFFER_REQUEST = 'CREATE_OFFER_REQUEST';
const CREATE_OFFER_SUCCESS = 'CREATE_OFFER_SUCCESS';
const CREATE_OFFER_FAILURE = 'CREATE_OFFER_FAILURE';

const GET_ALL_OFFERS_REQUEST = 'GET_ALL_OFFERS_REQUEST';
const GET_ALL_OFFERS_SUCCESS = 'GET_ALL_OFFERS_SUCCESS';
const GET_ALL_OFFERS_FAILURE = 'GET_ALL_OFFERS_FAILURE';

const GET_OFFER_BY_ID_REQUEST = 'GET_OFFER_BY_ID_REQUEST';
const GET_OFFER_BY_ID_SUCCESS = 'GET_OFFER_BY_ID_SUCCESS';
const GET_OFFER_BY_ID_FAILURE = 'GET_OFFER_BY_ID_FAILURE';

const UPDATE_OFFER_REQUEST = 'UPDATE_OFFER_REQUEST';
const UPDATE_OFFER_SUCCESS = 'UPDATE_OFFER_SUCCESS';
const UPDATE_OFFER_FAILURE = 'UPDATE_OFFER_FAILURE';

const DELETE_OFFER_REQUEST = 'DELETE_OFFER_REQUEST';
const DELETE_OFFER_SUCCESS = 'DELETE_OFFER_SUCCESS';
const DELETE_OFFER_FAILURE = 'DELETE_OFFER_FAILURE';

module.exports = {
  CREATE_OFFER_REQUEST,
  CREATE_OFFER_SUCCESS,
  CREATE_OFFER_FAILURE,
  GET_ALL_OFFERS_REQUEST,
  GET_ALL_OFFERS_SUCCESS,
  GET_ALL_OFFERS_FAILURE,
  GET_OFFER_BY_ID_REQUEST,
  GET_OFFER_BY_ID_SUCCESS,
  GET_OFFER_BY_ID_FAILURE,
  UPDATE_OFFER_REQUEST,
  UPDATE_OFFER_SUCCESS,
  UPDATE_OFFER_FAILURE,
  DELETE_OFFER_REQUEST,
  DELETE_OFFER_SUCCESS,
  DELETE_OFFER_FAILURE,
};
