// packageConstants.js

// Action types for package-related actions
const CREATE_PACKAGE_REQUEST = 'CREATE_PACKAGE_REQUEST';
const CREATE_PACKAGE_SUCCESS = 'CREATE_PACKAGE_SUCCESS';
const CREATE_PACKAGE_FAILURE = 'CREATE_PACKAGE_FAILURE';

const GET_ALL_PACKAGES_REQUEST = 'GET_ALL_PACKAGES_REQUEST';
const GET_ALL_PACKAGES_SUCCESS = 'GET_ALL_PACKAGES_SUCCESS';
const GET_ALL_PACKAGES_FAILURE = 'GET_ALL_PACKAGES_FAILURE';

const GET_PACKAGE_BY_ID_REQUEST = 'GET_PACKAGE_BY_ID_REQUEST';
const GET_PACKAGE_BY_ID_SUCCESS = 'GET_PACKAGE_BY_ID_SUCCESS';
const GET_PACKAGE_BY_ID_FAILURE = 'GET_PACKAGE_BY_ID_FAILURE';

const UPDATE_PACKAGE_REQUEST = 'UPDATE_PACKAGE_REQUEST';
const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS';
const UPDATE_PACKAGE_FAILURE = 'UPDATE_PACKAGE_FAILURE';

const DELETE_PACKAGE_REQUEST = 'DELETE_PACKAGE_REQUEST';
const DELETE_PACKAGE_SUCCESS = 'DELETE_PACKAGE_SUCCESS';
const DELETE_PACKAGE_FAILURE = 'DELETE_PACKAGE_FAILURE';

module.exports = {
  CREATE_PACKAGE_REQUEST,
  CREATE_PACKAGE_SUCCESS,
  CREATE_PACKAGE_FAILURE,
  GET_ALL_PACKAGES_REQUEST,
  GET_ALL_PACKAGES_SUCCESS,
  GET_ALL_PACKAGES_FAILURE,
  GET_PACKAGE_BY_ID_REQUEST,
  GET_PACKAGE_BY_ID_SUCCESS,
  GET_PACKAGE_BY_ID_FAILURE,
  UPDATE_PACKAGE_REQUEST,
  UPDATE_PACKAGE_SUCCESS,
  UPDATE_PACKAGE_FAILURE,
  DELETE_PACKAGE_REQUEST,
  DELETE_PACKAGE_SUCCESS,
  DELETE_PACKAGE_FAILURE,
};
