// PlaceConstants.js

export const PLACE_REQUEST = 'PLACE_REQUEST';
export const PLACE_SUCCESS = 'PLACE_SUCCESS';
export const PLACE_FAILURE = 'PLACE_FAILURE';

export const CREATE_PLACE_REQUEST = 'CREATE_PLACE_REQUEST';
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS';
export const CREATE_PLACE_FAILURE = 'CREATE_PLACE_FAILURE';

export const UPDATE_PLACE_REQUEST = 'UPDATE_PLACE_REQUEST';
export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS';
export const UPDATE_PLACE_FAILURE = 'UPDATE_PLACE_FAILURE';

export const DELETE_PLACE_REQUEST = 'DELETE_PLACE_REQUEST';
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS';
export const DELETE_PLACE_FAILURE = 'DELETE_PLACE_FAILURE';